// Generated by tools/generate_material_palette.py; edit COLORS there.
const uint COLOR_STONE = 0xff767067u;
const uint COLOR_SAND = 0xff73bedcu;
const uint COLOR_WET_SAND = 0xff71a4bfu;
const uint COLOR_DIRT = 0xff5192c8u;
const uint COLOR_MUD = 0xff4a7db9u;
const uint COLOR_GRAVEL = 0xff867e77u;
const uint COLOR_WATER = 0xffc0a069u;
const uint COLOR_GAS = 0xffc7b9abu;
