#ifndef DUNGEONCRAFT_APP_VIEW_CONFIG_H
#define DUNGEONCRAFT_APP_VIEW_CONFIG_H

#include "dungeoncraft/chunk.h"

#ifdef DC_NATIVE_VIEW
enum { VIEW_WIDTH = 1920, VIEW_HEIGHT = 1080, WINDOW_SCALE = 1,
       BRUSH_RADIUS = 12, FLUID_INTERVAL = 6, INITIAL_CHUNK_Y = -8,
       WORLD_SCALE = 4, SPRING_RADIUS = 2 };
#elif defined(DC_HALF_NATIVE_VIEW)
enum { VIEW_WIDTH = 960, VIEW_HEIGHT = 540, WINDOW_SCALE = 2,
       BRUSH_RADIUS = 6, FLUID_INTERVAL = 3, INITIAL_CHUNK_Y = -4,
       WORLD_SCALE = 2, SPRING_RADIUS = 2 };
#elif defined(DC_QUARTER_NATIVE_VIEW)
enum { VIEW_WIDTH = 480, VIEW_HEIGHT = 270, WINDOW_SCALE = 4,
       BRUSH_RADIUS = 3, FLUID_INTERVAL = 1, INITIAL_CHUNK_Y = -2,
       WORLD_SCALE = 1, SPRING_RADIUS = 1 };
#else
enum { VIEW_WIDTH = 256, VIEW_HEIGHT = 128, WINDOW_SCALE = 4,
       BRUSH_RADIUS = 3, FLUID_INTERVAL = 1, INITIAL_CHUNK_Y = 0,
       WORLD_SCALE = 1, SPRING_RADIUS = 2 };
#endif

enum { VIEW_CHUNKS_X = (VIEW_WIDTH + DC_CHUNK_SIDE - 1) / DC_CHUNK_SIDE,
       VIEW_CHUNKS_Y = (VIEW_HEIGHT + DC_CHUNK_SIDE - 1) / DC_CHUNK_SIDE,
       HALO_CHUNKS = 1,
       SIM_CHUNKS_X = VIEW_CHUNKS_X + 2 * HALO_CHUNKS,
       SIM_CHUNKS_Y = VIEW_CHUNKS_Y + 2 * HALO_CHUNKS,
       SIM_WIDTH = SIM_CHUNKS_X * DC_CHUNK_SIDE,
       SIM_HEIGHT = SIM_CHUNKS_Y * DC_CHUNK_SIDE };

#endif
