"""Generate perceptual material colors and a 16-bit pixel-art ramp preview.

The OKLCH-to-linear-sRGB transform follows Bjorn Ottosson's public-domain
Oklab reference: https://bottosson.github.io/posts/oklab/
Run from any directory: python3 tools/generate_material_palette.py
"""

from math import cos, radians, sin
from pathlib import Path
from struct import pack


ROOT = Path(__file__).resolve().parents[1]
COLORS = {
    "STONE": (0.54, 0.015, 235),
    "SAND": (0.81, 0.10, 88),
    "WET_SAND": (0.73, 0.075, 83),
    "DIRT": (0.70, 0.105, 70),
    "MUD": (0.64, 0.10, 60),
    "GRAVEL": (0.59, 0.015, 250),
    "WATER": (0.68, 0.075, 235),
}


def linear_rgb(lightness, chroma, hue):
    a = chroma * cos(radians(hue))
    b = chroma * sin(radians(hue))
    l = (lightness + 0.3963377774 * a + 0.2158037573 * b) ** 3
    m = (lightness - 0.1055613458 * a - 0.0638541728 * b) ** 3
    s = (lightness - 0.0894841775 * a - 1.2914855480 * b) ** 3
    return (
        4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
        -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
        -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s,
    )


def srgb_channel(value):
    value = min(1.0, max(0.0, value))
    return 12.92 * value if value <= 0.0031308 else 1.055 * value ** (1 / 2.4) - 0.055


def packed_color(lab):
    rgb = [round(255 * srgb_channel(value)) for value in linear_rgb(*lab)]
    return 0xFF000000 | rgb[2] << 16 | rgb[1] << 8 | rgb[0]


def write_shader_palette():
    lines = ["// Generated by tools/generate_material_palette.py; edit COLORS there."]
    lines += [f"const uint COLOR_{name} = 0x{packed_color(lab):08x}u;"
              for name, lab in COLORS.items()]
    path = ROOT / "shaders/sim/material_palette.glsl"
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def write_preview():
    samples = [linear_rgb(*lab) for lab in COLORS.values()]
    water = samples[-1]
    mud = samples[4]
    width, height = 1024, 96
    path = ROOT / "build/material_palette_16.ppm"
    path.parent.mkdir(exist_ok=True)
    with path.open("wb") as output:
        output.write(f"P6\n{width} {height}\n65535\n".encode("ascii"))
        for y in range(height):
            for x in range(width):
                if y < 48:
                    color = samples[min(x * len(samples) // width, len(samples) - 1)]
                else:
                    dirt_fraction = x / (width - 1)
                    color = tuple((1 - dirt_fraction) * w + dirt_fraction * m
                                  for w, m in zip(water, mud))
                output.write(pack(">HHH", *(round(65535 * srgb_channel(c))
                                               for c in color)))
    print(path)


if __name__ == "__main__":
    write_shader_palette()
    write_preview()
